version: "3.3"
services:
  client:
    image: node:12.16.3
    container_name: Riftuo_Client
    ports:
      - "3000:3000"
    working_dir: /riftuo/client
    volumes:
      - ./client:/riftuo/client
    entrypoint: ["npm", "start"]
    stdin_open: true

  server:
    build: ./server
    container_name: Riftuo_Server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/riftuo/server
      - /server/node_modules
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: Riftuo_MongoDB
    volumes:
      - ./riftuo-db:/data/db
    command: mongod --noauth
    restart: always
    ports:
      - 27018:27017
